# Generated by Django 5.1.7 on 2025-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.TextField(blank=True, help_text='Comma-separated list of facilities (e.g., Wi-Fi, AC)'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
