# Generated by Django 5.1.7 on 2025-03-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_created_at_remove_room_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
